export const DUY_NHAT_LYRICS = {
    1: "Em có lẽ không biết điều này",
    9: "Từ lúc đón đưa dưới hiên nhà",
    17: "Anh biết mình hồi hộp mỗi khi",
    23: "Trò chuyện với em",
    27: "Ngập ngừng, ngại ngùng, bối rối",
    33: "Viết bài hát tình ca xin tặng",
    40: "Gửi tới Mặt Xinh Nhưng Hay Giận",
    48: "Yêu em từ những điều giản đơn",
    53: "Chỉ vài lần nhắn tin",
    58: "Cũng làm tim anh xuyến xao",
    64: "Anh chẳng cần những thứ cao sang cầu kỳ",
    72: "Vì anh chỉ cần một thứ hơn cả điều gì",
    80: "Là nụ cười toả sáng khắp cả bầu trời mỗi khi em nhìn anh",
    // 83: "Mỗi khi em nhìn anh",
    87: "Và ánh mắt nâu trầm",
    91: "Hàng triệu tinh tú long lanh",
    95: "Dù mai mưa to hay gió bão giông ngập lụt",
    104: "Thì anh là người che chở em qua ngày buồn",
    111: "Từ giờ tới ngàn năm nữa",
    114: "Anh vẫn luôn và sẽ yêu em",
    119: "Vì em là người duy nhất trong anh mà thôi",
    125: "(Nhạc dạo)",
    136: "Nhớ rằng anh yêu thật lòng",
    143: "Dù cuộc sống chẳng thể biết trước điều gì",
    151: "Nhưng chỉ cần ta luôn vững tin",
    157: "Thì mọi điều lắng lo",
    160: "Cũng chẳng làm ta đắn đo",
    167: "Vì yêu anh sẽ bất chấp hết những gian nguy",
    175: "Không làm em suy nghĩ lo âu điều gì",
    181: "Để nụ cười luôn toả sáng khắp cả bầu trời mỗi khi ta nhìn nhau",
    190: "Dẫu có thăng trầm thì đừng lo nhé em à",
    197: "Vì dù mai mưa to hay gió bão giông ngập lụt",
    205: "Anh là người che chở em qua ngày buồn",
    213: "Cuộc đời cho dù bão tố",
    217: "Nụ cười vụt tắt trên môi",
    220: "Điều duy nhất em cần làm là gọi cho tôi",
    230: "Dù mai mưa to hay gió bão giông ngập lụt",
    238: "Thì anh là người che chở em qua ngày buồn",
    246: "Khi bão tố cuộc đời làm em mất đi nụ cười trên môi",
    251: "Thì điều duy nhất em cần làm là gọi cho tôi"
}
